#!/bin/bash

source "$OMEGA_ROOT"/.omega-cfg
source "$OMEGA_ROOT"/toolbox.sh

case "$1" in
    "new") "$OMEGA_ROOT"/new.sh;;
    "list") "$OMEGA_ROOT"/list.sh;;
    "") omega_speach "Heya §pcomrade§b§b !" \
              && omega_speach "Feel free to type §phelp§n§b or §p?§n§b if you're lost";;
    "help" | "?") "$OMEGA_ROOT"/help.sh ;;
    *) omega_speach "What the hell does §p$1§n§b mean ? I don't know about that "$pale"mate"
esac
